spring:
  profiles:
    active: pro
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  tomcat:
    connection-timeout: 180000

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/work5?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 222316
  data:
    redis:
      host: 192.168.190.133
      port: 6379
      password: 222316
      database: 0
my:
 secret: ygh112233
logging:
  level:
    mybatis-plus: DEBUG
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---

server:
  port: 80
spring:
  config:
    activate:
      on-profile: pro
  datasource:
    url: jdbc:mysql://47.120.38.239:3306/work5?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 222316
  data:
    redis:
      host: 47.120.38.239
      port: 6379
      password: 222316
      database: 0
my:
 secret: ygh112233
logging:
  level:
    root: ERROR
    mybatis-plus: ERROR
    '[org.springframework]': ERROR
  file:
    path: /root/work5
